name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action every day at midnight. Adjust the schedule as needed.
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab.

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/KelvinTegelaar/CIPP-API.git
        git fetch upstream

    - name: Create new branch
      run: |
        git checkout -b sync-upstream

    - name: Pull and rebase main branch
      run: |
        git pull --rebase upstream main || (
          git rebase --abort &&
          git pull --rebase -s recursive -X ours upstream main
        )

    - name: Push changes to new branch
      run: |
        git push origin sync-upstream --force
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: Sync with upstream
        branch: sync-upstream
        base: main
        title: 'Sync with upstream'
        body: 'This PR merges changes from the upstream repository into the forked repository.'
        labels: 'sync'
